/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginInputInput"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    namespace?: "canonical" | "custom";
                    kind?: "numeric" | "categorical" | "geo" | "composite" | "session" | "event";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            entries: components["schemas"]["CatalogueEntry"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue/aliases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            aliases: components["schemas"]["CatalogueAlias"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAliasInput"];
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CatalogueAlias"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CatalogueEntry"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue/custom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCustomEntryInput"];
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CatalogueEntry"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["IngestRequestInput"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IngestResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReplayRequestInput"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReplayResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeviceList"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterDeviceInput"];
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Device"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateDeviceInput"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Device"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/sync/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    source_integration?: string;
                    source_device?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SyncLatest"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserInput: {
            id: string;
            username: string | null;
            /** @enum {string} */
            role: "admin" | "user";
            created_at: string;
        };
        LoginInputInput: {
            username: string;
            password: string;
        };
        LoginResponseInput: {
            token: string;
            user: components["schemas"]["UserInput"];
        };
        CatalogueEntryInput: {
            id: string;
            /** @enum {string} */
            namespace: "canonical" | "custom";
            version: number;
            description: string | null;
            deprecated: boolean;
            created_at: string;
            updated_at: string;
            /** @constant */
            kind: "numeric";
            config: {
                unit: string;
                range?: {
                    min: number;
                    max: number;
                };
            };
        } | {
            id: string;
            /** @enum {string} */
            namespace: "canonical" | "custom";
            version: number;
            description: string | null;
            deprecated: boolean;
            created_at: string;
            updated_at: string;
            /** @constant */
            kind: "categorical";
            config: {
                values: string[];
            };
        } | {
            id: string;
            /** @enum {string} */
            namespace: "canonical" | "custom";
            version: number;
            description: string | null;
            deprecated: boolean;
            created_at: string;
            updated_at: string;
            /** @constant */
            kind: "geo";
            config: Record<string, never>;
        } | {
            id: string;
            /** @enum {string} */
            namespace: "canonical" | "custom";
            version: number;
            description: string | null;
            deprecated: boolean;
            created_at: string;
            updated_at: string;
            /** @constant */
            kind: "composite";
            config: {
                components: {
                    [key: string]: {
                        unit: string;
                        range?: {
                            min: number;
                            max: number;
                        };
                    };
                };
            };
        } | {
            id: string;
            /** @enum {string} */
            namespace: "canonical" | "custom";
            version: number;
            description: string | null;
            deprecated: boolean;
            created_at: string;
            updated_at: string;
            /** @constant */
            kind: "session";
            config: Record<string, never>;
        } | {
            id: string;
            /** @enum {string} */
            namespace: "canonical" | "custom";
            version: number;
            description: string | null;
            deprecated: boolean;
            created_at: string;
            updated_at: string;
            /** @constant */
            kind: "event";
            config: {
                schema: {
                    [key: string]: unknown;
                };
            };
        };
        CatalogueAliasInput: {
            alias: string;
            canonical_id: string;
            created_at: string;
        };
        CreateCustomEntryInput: {
            id: string;
            /** @constant */
            kind: "numeric";
            description?: string;
            config: {
                unit: string;
                range?: {
                    min: number;
                    max: number;
                };
            };
        } | {
            id: string;
            /** @constant */
            kind: "categorical";
            description?: string;
            config: {
                values: string[];
            };
        } | {
            id: string;
            /** @constant */
            kind: "geo";
            description?: string;
            /** @default {} */
            config: Record<string, never>;
        } | {
            id: string;
            /** @constant */
            kind: "composite";
            description?: string;
            config: {
                components: {
                    [key: string]: {
                        unit: string;
                        range?: {
                            min: number;
                            max: number;
                        };
                    };
                };
            };
        } | {
            id: string;
            /** @constant */
            kind: "session";
            description?: string;
            /** @default {} */
            config: Record<string, never>;
        } | {
            id: string;
            /** @constant */
            kind: "event";
            description?: string;
            config: {
                schema: {
                    [key: string]: unknown;
                };
            };
        };
        CreateAliasInput: {
            alias: string;
            canonical_id: string;
        };
        DeviceInput: {
            id: string;
            integration: string;
            device_id: string;
            name: string;
            created_at: string;
            updated_at: string;
        };
        DeviceListInput: {
            devices: components["schemas"]["DeviceInput"][];
        };
        RegisterDeviceInput: {
            integration: string;
            device_id: string;
            name: string;
        };
        UpdateDeviceInput: {
            name: string;
        };
        IngestRequestInput: {
            source: {
                integration: string;
                device: string;
                instance?: string;
            };
            items: ({
                /** @constant */
                type: "sample";
                idempotency_key: string;
                metric: string;
                /** Format: date-time */
                start: string;
                /** Format: date-time */
                end: string;
                tz?: string;
                value: unknown;
                session_idempotency_key?: string;
            } | {
                /** @constant */
                type: "session";
                idempotency_key: string;
                session_type: string;
                /** Format: date-time */
                start: string;
                /** Format: date-time */
                end: string;
                tz?: string;
                metadata?: {
                    [key: string]: unknown;
                };
            } | {
                /** @constant */
                type: "event";
                idempotency_key: string;
                metric: string;
                /** Format: date-time */
                at: string;
                tz?: string;
                payload: {
                    [key: string]: unknown;
                };
                session_idempotency_key?: string;
            } | {
                /** @constant */
                type: "annotation";
                idempotency_key: string;
                /** Format: date-time */
                start: string;
                /** Format: date-time */
                end: string;
                tz?: string;
                text: string;
                tags?: string[];
            })[];
        };
        IngestResponseInput: {
            results: ({
                idempotency_key: string;
                /** @constant */
                status: "accepted";
                id: string;
            } | {
                idempotency_key: string;
                /** @constant */
                status: "rejected";
                /** @enum {string} */
                reason: "unknown_metric" | "invalid_value_kind" | "schema_mismatch" | "out_of_range" | "missing_field" | "invalid_timestamp" | "catalogue_deprecated";
                detail?: string;
            })[];
        };
        ReplayRequestInput: {
            user_id?: string;
            metric?: string;
            source_integration?: string;
            /** @enum {string} */
            rejection_reason?: "unknown_metric" | "invalid_value_kind" | "schema_mismatch" | "out_of_range" | "missing_field" | "invalid_timestamp" | "catalogue_deprecated";
            /** @default 1000 */
            limit: number;
        };
        ReplayResponseInput: {
            attempted: number;
            promoted: number;
            still_rejected: number;
        };
        HighWaterMarkInput: {
            source_integration: string;
            source_device: string;
            metric: string;
            latest_at: string;
        };
        SyncLatestInput: {
            samples: components["schemas"]["HighWaterMarkInput"][];
            events: components["schemas"]["HighWaterMarkInput"][];
            sessions: components["schemas"]["HighWaterMarkInput"][];
        };
        User: {
            id: string;
            username: string | null;
            /** @enum {string} */
            role: "admin" | "user";
            created_at: string;
        };
        LoginInput: {
            username: string;
            password: string;
        };
        LoginResponse: {
            token: string;
            user: components["schemas"]["User"];
        };
        CatalogueEntry: {
            id: string;
            /** @enum {string} */
            namespace: "canonical" | "custom";
            version: number;
            description: string | null;
            deprecated: boolean;
            created_at: string;
            updated_at: string;
            /** @constant */
            kind: "numeric";
            config: {
                unit: string;
                range?: {
                    min: number;
                    max: number;
                };
            };
        } | {
            id: string;
            /** @enum {string} */
            namespace: "canonical" | "custom";
            version: number;
            description: string | null;
            deprecated: boolean;
            created_at: string;
            updated_at: string;
            /** @constant */
            kind: "categorical";
            config: {
                values: string[];
            };
        } | {
            id: string;
            /** @enum {string} */
            namespace: "canonical" | "custom";
            version: number;
            description: string | null;
            deprecated: boolean;
            created_at: string;
            updated_at: string;
            /** @constant */
            kind: "geo";
            config: Record<string, never>;
        } | {
            id: string;
            /** @enum {string} */
            namespace: "canonical" | "custom";
            version: number;
            description: string | null;
            deprecated: boolean;
            created_at: string;
            updated_at: string;
            /** @constant */
            kind: "composite";
            config: {
                components: {
                    [key: string]: {
                        unit: string;
                        range?: {
                            min: number;
                            max: number;
                        };
                    };
                };
            };
        } | {
            id: string;
            /** @enum {string} */
            namespace: "canonical" | "custom";
            version: number;
            description: string | null;
            deprecated: boolean;
            created_at: string;
            updated_at: string;
            /** @constant */
            kind: "session";
            config: Record<string, never>;
        } | {
            id: string;
            /** @enum {string} */
            namespace: "canonical" | "custom";
            version: number;
            description: string | null;
            deprecated: boolean;
            created_at: string;
            updated_at: string;
            /** @constant */
            kind: "event";
            config: {
                schema: {
                    [key: string]: unknown;
                };
            };
        };
        CatalogueAlias: {
            alias: string;
            canonical_id: string;
            created_at: string;
        };
        CreateCustomEntry: {
            id: string;
            /** @constant */
            kind: "numeric";
            description?: string;
            config: {
                unit: string;
                range?: {
                    min: number;
                    max: number;
                };
            };
        } | {
            id: string;
            /** @constant */
            kind: "categorical";
            description?: string;
            config: {
                values: string[];
            };
        } | {
            id: string;
            /** @constant */
            kind: "geo";
            description?: string;
            /** @default {} */
            config: Record<string, never>;
        } | {
            id: string;
            /** @constant */
            kind: "composite";
            description?: string;
            config: {
                components: {
                    [key: string]: {
                        unit: string;
                        range?: {
                            min: number;
                            max: number;
                        };
                    };
                };
            };
        } | {
            id: string;
            /** @constant */
            kind: "session";
            description?: string;
            /** @default {} */
            config: Record<string, never>;
        } | {
            id: string;
            /** @constant */
            kind: "event";
            description?: string;
            config: {
                schema: {
                    [key: string]: unknown;
                };
            };
        };
        CreateAlias: {
            alias: string;
            canonical_id: string;
        };
        Device: {
            id: string;
            integration: string;
            device_id: string;
            name: string;
            created_at: string;
            updated_at: string;
        };
        DeviceList: {
            devices: components["schemas"]["Device"][];
        };
        RegisterDevice: {
            integration: string;
            device_id: string;
            name: string;
        };
        UpdateDevice: {
            name: string;
        };
        IngestRequest: {
            source: {
                integration: string;
                device: string;
                instance?: string;
            };
            items: ({
                /** @constant */
                type: "sample";
                idempotency_key: string;
                metric: string;
                /** Format: date-time */
                start: string;
                /** Format: date-time */
                end: string;
                tz?: string;
                value: unknown;
                session_idempotency_key?: string;
            } | {
                /** @constant */
                type: "session";
                idempotency_key: string;
                session_type: string;
                /** Format: date-time */
                start: string;
                /** Format: date-time */
                end: string;
                tz?: string;
                metadata?: {
                    [key: string]: unknown;
                };
            } | {
                /** @constant */
                type: "event";
                idempotency_key: string;
                metric: string;
                /** Format: date-time */
                at: string;
                tz?: string;
                payload: {
                    [key: string]: unknown;
                };
                session_idempotency_key?: string;
            } | {
                /** @constant */
                type: "annotation";
                idempotency_key: string;
                /** Format: date-time */
                start: string;
                /** Format: date-time */
                end: string;
                tz?: string;
                text: string;
                tags?: string[];
            })[];
        };
        IngestResponse: {
            results: ({
                idempotency_key: string;
                /** @constant */
                status: "accepted";
                id: string;
            } | {
                idempotency_key: string;
                /** @constant */
                status: "rejected";
                /** @enum {string} */
                reason: "unknown_metric" | "invalid_value_kind" | "schema_mismatch" | "out_of_range" | "missing_field" | "invalid_timestamp" | "catalogue_deprecated";
                detail?: string;
            })[];
        };
        ReplayRequest: {
            user_id?: string;
            metric?: string;
            source_integration?: string;
            /** @enum {string} */
            rejection_reason?: "unknown_metric" | "invalid_value_kind" | "schema_mismatch" | "out_of_range" | "missing_field" | "invalid_timestamp" | "catalogue_deprecated";
            /** @default 1000 */
            limit: number;
        };
        ReplayResponse: {
            attempted: number;
            promoted: number;
            still_rejected: number;
        };
        HighWaterMark: {
            source_integration: string;
            source_device: string;
            metric: string;
            latest_at: string;
        };
        SyncLatest: {
            samples: components["schemas"]["HighWaterMark"][];
            events: components["schemas"]["HighWaterMark"][];
            sessions: components["schemas"]["HighWaterMark"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
